//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AF.WINFORMS.DX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AF.WINFORMS.DX.WinFormsStrings", typeof(WinFormsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert für den Parameter..
        /// </summary>
        internal static string BOL_DEFAULT_LONG {
            get {
                return ResourceManager.GetString("BOL_DEFAULT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert.
        /// </summary>
        internal static string BOL_DEFAULT_SHORT {
            get {
                return ResourceManager.GetString("BOL_DEFAULT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabe als Text.
        /// </summary>
        internal static string BOL_OUTASTEXT_SHORT {
            get {
                return ResourceManager.GetString("BOL_OUTASTEXT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abbrechen.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignorieren.
        /// </summary>
        internal static string BTN_IGNORE {
            get {
                return ResourceManager.GetString("BTN_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nein.
        /// </summary>
        internal static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wiederholen.
        /// </summary>
        internal static string BTN_RETRY {
            get {
                return ResourceManager.GetString("BTN_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ja.
        /// </summary>
        internal static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START
        ///Die Anwendung läuft bereits und kann nicht ein zweites Mal gestartet werden..
        /// </summary>
        internal static string CANTSTARTUPTWICE {
            get {
                return ResourceManager.GetString("CANTSTARTUPTWICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen....
        /// </summary>
        internal static string CMDDELETE_CAPTION {
            get {
                return ResourceManager.GetString("CMDDELETE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten....
        /// </summary>
        internal static string CMDEDIT_CAPTION {
            get {
                return ResourceManager.GetString("CMDEDIT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren....
        /// </summary>
        internal static string CMDEXPORT_CAPTION {
            get {
                return ResourceManager.GetString("CMDEXPORT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe zu....
        /// </summary>
        internal static string CMDGOTO_CAPTION {
            get {
                return ResourceManager.GetString("CMDGOTO_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importieren....
        /// </summary>
        internal static string CMDIMPORT_CAPTION {
            get {
                return ResourceManager.GetString("CMDIMPORT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu....
        /// </summary>
        internal static string CMDNEW_CAPTION {
            get {
                return ResourceManager.GetString("CMDNEW_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu aus Kopie....
        /// </summary>
        internal static string CMDNEWCOPY_CAPTION {
            get {
                return ResourceManager.GetString("CMDNEWCOPY_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert für den Parameter..
        /// </summary>
        internal static string DEC_DEFAULT_LONG {
            get {
                return ResourceManager.GetString("DEC_DEFAULT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert.
        /// </summary>
        internal static string DEC_DEFAULT_SHORT {
            get {
                return ResourceManager.GetString("DEC_DEFAULT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximaler Wert für den Parameter. Der Benutzer kann keine höheren Werte als diesen auswählen..
        /// </summary>
        internal static string DEC_MAXIMUM_LONG {
            get {
                return ResourceManager.GetString("DEC_MAXIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string DEC_MAXIMUM_SHORT {
            get {
                return ResourceManager.GetString("DEC_MAXIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimaler Wert für den Parameter. Der Benutzer kann keine kleineren Werte als diesen auswählen..
        /// </summary>
        internal static string DEC_MINIMUM_LONG {
            get {
                return ResourceManager.GetString("DEC_MINIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string DEC_MINIMUM_SHORT {
            get {
                return ResourceManager.GetString("DEC_MINIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabe als Text.
        /// </summary>
        internal static string DEC_OUTASTEXT_SHORT {
            get {
                return ResourceManager.GetString("DEC_OUTASTEXT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER
        ///{0}
        ///({1}).
        /// </summary>
        internal static string ERR_HANDLECMDRESULTERROR {
            get {
                return ResourceManager.GetString("ERR_HANDLECMDRESULTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Anmeldename muss mindestens 5 Zeichen lang sein..
        /// </summary>
        internal static string ERR_LOGINNAMETOSHORT {
            get {
                return ResourceManager.GetString("ERR_LOGINNAMETOSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen Mandanten ausgewählt..
        /// </summary>
        internal static string ERR_NOCLIENTSELECTED {
            get {
                return ResourceManager.GetString("ERR_NOCLIENTSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Model vom Typ {0} mit der ID {1} gefunden..
        /// </summary>
        internal static string ERR_NOMODELWITHID {
            get {
                return ResourceManager.GetString("ERR_NOMODELWITHID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kennwort muss mindestens 8 Zeichen lang sein..
        /// </summary>
        internal static string ERR_PASSWORDTOSHORT {
            get {
                return ResourceManager.GetString("ERR_PASSWORDTOSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekanntes Dateiformat / unbekannte Dateiendung..
        /// </summary>
        internal static string ERR_UNKNOWNFILEFORMAT {
            get {
                return ResourceManager.GetString("ERR_UNKNOWNFILEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Vorgabe für MessageBoxButtons..
        /// </summary>
        internal static string ERR_UNKNOWNMSGBUTTONS {
            get {
                return ResourceManager.GetString("ERR_UNKNOWNMSGBUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wiederholung stimmt nicht mit dem Kennwort überein..
        /// </summary>
        internal static string ERR_WRONGPASSWORDREPEAT {
            get {
                return ResourceManager.GetString("ERR_WRONGPASSWORDREPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel-Datei|*.xlsx|CSV-Datei|*.csv|PDF-Datei|*.pdf|Word-Datei|*.docx|HTML-Datei|*.html|RTF-Datei|*.rtf|Alle Dateien|*.*.
        /// </summary>
        internal static string GRID_EXPORTFILTER {
            get {
                return ResourceManager.GetString("GRID_EXPORTFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorieren.
        /// </summary>
        internal static string IGNORE {
            get {
                return ResourceManager.GetString("IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert für den Parameter..
        /// </summary>
        internal static string INT_DEFAULT_LONG {
            get {
                return ResourceManager.GetString("INT_DEFAULT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert.
        /// </summary>
        internal static string INT_DEFAULT_SHORT {
            get {
                return ResourceManager.GetString("INT_DEFAULT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höchstwert für den Parameter. Der Benutzer kann keine höheren Werte als diesen auswählen..
        /// </summary>
        internal static string INT_MAXIMUM_LONG {
            get {
                return ResourceManager.GetString("INT_MAXIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string INT_MAXIMUM_SHORT {
            get {
                return ResourceManager.GetString("INT_MAXIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestwert für den Parameter. Der Benutzer kann keine kleineren Werte als diesen auswählen..
        /// </summary>
        internal static string INT_MINIMUM_LONG {
            get {
                return ResourceManager.GetString("INT_MINIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string INT_MINIMUM_SHORT {
            get {
                return ResourceManager.GetString("INT_MINIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabe als Text.
        /// </summary>
        internal static string INT_OUTASTEXT_SHORT {
            get {
                return ResourceManager.GetString("INT_OUTASTEXT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung wird geladen....
        /// </summary>
        internal static string LBL_APPLOADING {
            get {
                return ResourceManager.GetString("LBL_APPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandant wird geladen....
        /// </summary>
        internal static string LBL_CLIENTLOADING {
            get {
                return ResourceManager.GetString("LBL_CLIENTLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Administrator anlegen.
        /// </summary>
        internal static string LBL_CREATEADMIN {
            get {
                return ResourceManager.GetString("LBL_CREATEADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string LBL_DELETE {
            get {
                return ResourceManager.GetString("LBL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string LBL_EDIT {
            get {
                return ResourceManager.GetString("LBL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Datei exportieren....
        /// </summary>
        internal static string LBL_EXPORTTOFILE {
            get {
                return ResourceManager.GetString("LBL_EXPORTTOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehe zu.
        /// </summary>
        internal static string LBL_GOTO {
            get {
                return ResourceManager.GetString("LBL_GOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte anmelden....
        /// </summary>
        internal static string LBL_LOGIN {
            get {
                return ResourceManager.GetString("LBL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string LBL_NEW {
            get {
                return ResourceManager.GetString("LBL_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITTE MANDANTEN AUSWÄHLEN.
        /// </summary>
        internal static string LBL_SELECTMANDANT {
            get {
                return ResourceManager.GetString("LBL_SELECTMANDANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details anzeigen.
        /// </summary>
        internal static string LBL_SHOWDETAILS {
            get {
                return ResourceManager.GetString("LBL_SHOWDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr Informationen.
        /// </summary>
        internal static string LBL_SHOWMOREINFO {
            get {
                return ResourceManager.GetString("LBL_SHOWMOREINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten....
        /// </summary>
        internal static string LBL_WAIT {
            get {
                return ResourceManager.GetString("LBL_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert, der verwendet wird, wenn der Benutzer dieses Element auswählt..
        /// </summary>
        internal static string LSE_VALUE_LONG {
            get {
                return ResourceManager.GetString("LSE_VALUE_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        internal static string LSE_VALUE_SHORT {
            get {
                return ResourceManager.GetString("LSE_VALUE_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardwert für den Parameter..
        /// </summary>
        internal static string LST_DEFAULT_LONG {
            get {
                return ResourceManager.GetString("LST_DEFAULT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardwert.
        /// </summary>
        internal static string LST_DEFAULT_SHORT {
            get {
                return ResourceManager.GetString("LST_DEFAULT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr Informationen.
        /// </summary>
        internal static string MOREINFORMATIONS {
            get {
                return ResourceManager.GetString("MOREINFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT
        ///Beim Export trat ein Fehler auf.
        ///.
        /// </summary>
        internal static string MSG_EXPORTERROR {
            get {
                return ResourceManager.GetString("MSG_EXPORTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT
        ///Daten wurden erfolgreich exportiert..
        /// </summary>
        internal static string MSG_EXPORTSUCCESS {
            get {
                return ResourceManager.GetString("MSG_EXPORTSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUELLCODE BEARBEITEN
        ///Wenn Sie in den Quellcode-Modus wechseln, verlieren Sie Ihr aktuelles Design-Schema. Ihre aktuelle Abfrage wird in den Quellcode verschoben. Sind Sie sicher?.
        /// </summary>
        internal static string MSG_SWITCHTOCODE {
            get {
                return ResourceManager.GetString("MSG_SWITCHTOCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESIGNER VERWENDEN
        ///Wenn Sie in den Designmodus wechseln, verlieren Sie Ihren aktuellen Quellcode der Abfrage. Sind Sie sicher?.
        /// </summary>
        internal static string MSG_SWITCHTODESIGNER {
            get {
                return ResourceManager.GetString("MSG_SWITCHTODESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Beschreibung dieses Parameters für den Benutzer der Abfrage..
        /// </summary>
        internal static string PAR_CAPTION_LONG {
            get {
                return ResourceManager.GetString("PAR_CAPTION_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterbeschreibung.
        /// </summary>
        internal static string PAR_DESC_SHORT {
            get {
                return ResourceManager.GetString("PAR_DESC_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis zu diesem Parameter, der dem Benutzer in einem Tooltip angezeigt wird..
        /// </summary>
        internal static string PAR_HINT_LONG {
            get {
                return ResourceManager.GetString("PAR_HINT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter-Tipp.
        /// </summary>
        internal static string PAR_HINT_SHORT {
            get {
                return ResourceManager.GetString("PAR_HINT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um den Parameter in der Abfrage zu verwenden, stellen Sie dem Namen ein @-Zeichen voran (Beispiel: FIELDNAME &gt; @name)..
        /// </summary>
        internal static string PAR_NAME_HINT {
            get {
                return ResourceManager.GetString("PAR_NAME_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Parameters. Dieser Name wird für die Verwendung des Parameters in der Abfrage verwendet..
        /// </summary>
        internal static string PAR_NAME_LONG {
            get {
                return ResourceManager.GetString("PAR_NAME_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametername.
        /// </summary>
        internal static string PAR_NAME_SHORT {
            get {
                return ResourceManager.GetString("PAR_NAME_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        internal static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        internal static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LexScheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Name&gt;PowerShell language&lt;/Name&gt;
        ///  &lt;Desc&gt;Syntax Scheme for PowerShell Language&lt;/Desc&gt;
        ///  &lt;Copyright&gt;Copyright AlterNET Software, 2016-2019&lt;/Copyright&gt;
        ///  &lt;FileExtension&gt;.ps1&lt;/FileExtension&gt;
        ///  &lt;FileType&gt;powershell&lt;/FileType&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SYNTAX_POWERSHELL {
            get {
                return ResourceManager.GetString("SYNTAX_POWERSHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .root {
        ///	background-color:@Window;
        ///	color:@WindowText;
        ///}
        ///
        ///.container {
        ///	padding:6px;
        ///}
        ///
        ///.card {
        ///	font: 13px &apos;Segoe UI&apos;;
        ///	border-radius:3px;
        ///	background-color:@Window;
        ///	box-shadow:0px 1px 2px 0px #20000000;
        ///	color:@WindowText;
        ///	display:flex;
        ///}
        ///
        ///:root:select .card {
        ///	background-color:@Highlight/0.3;
        ///	box-shadow:0px 2px 5px 0px #40000000;
        ///}
        ///
        ///.stripe {
        ///	width:4px;
        ///	border-radius:3px 0px 0px 3px;
        ///}
        ///.content {
        ///	width:100%;
        ///	padding:12px;
        ///	display:flex;
        ///	flex-direction:column;
        ///}
        ///.t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TILEVIEWTEMPLATE_CSS {
            get {
                return ResourceManager.GetString("TILEVIEWTEMPLATE_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;container&quot;&gt;
        ///	&lt;div class=&quot;card&quot;&gt;
        ///		&lt;div class=&quot;stripe&quot; id=&quot;stripe&quot;&gt;&lt;/div&gt;
        ///		&lt;div class=&quot;content&quot;&gt;
        ///			&lt;div class=&quot;top-block&quot;&gt;
        ///				&lt;div class=&quot;caption&quot; id=&quot;caption&quot;&gt;&lt;b&gt;${FIR_NAMEEINZEILIG}&lt;/b&gt;&lt;/div&gt;
        ///				&lt;div class=&quot;statuslink&quot; id=&quot;link&quot;&gt;LINK&lt;/div&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;status&quot; id=&quot;important&quot;&gt;WICHTIG&lt;/div&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;status&quot; id=&quot;status&quot;&gt;${AUF_STATUS_TEXT}&lt;/div&gt; 
        ///			&lt;/div&gt;
        ///			&lt;div class=&quot;description&quot;&gt;${AUF_AUFGABE}&lt;/div&gt;
        ///			&lt;div class=&quot;bottom-block&quot;&gt;
        ///				&lt;div class=&quot;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TILEVIEWTEMPLATE_HTML {
            get {
                return ResourceManager.GetString("TILEVIEWTEMPLATE_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert für den Parameter..
        /// </summary>
        internal static string TXT_DEFAULT_LONG {
            get {
                return ResourceManager.GetString("TXT_DEFAULT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgabewert.
        /// </summary>
        internal static string TXT_DEFAULT_SHORT {
            get {
                return ResourceManager.GetString("TXT_DEFAULT_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximaler Wert für den Parameter. Der Benutzer kann keine höheren Werte als diesen auswählen..
        /// </summary>
        internal static string TXT_MAXIMUM_LONG {
            get {
                return ResourceManager.GetString("TXT_MAXIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string TXT_MAXIMUM_SHORT {
            get {
                return ResourceManager.GetString("TXT_MAXIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimaler Wert für den Parameter. Der Benutzer kann keine kleineren Werte als diesen auswählen..
        /// </summary>
        internal static string TXT_MINIMUM_LONG {
            get {
                return ResourceManager.GetString("TXT_MINIMUM_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string TXT_MINIMUM_SHORT {
            get {
                return ResourceManager.GetString("TXT_MINIMUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
