//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AF.CORE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AF.CORE.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string APRIL {
            get {
                return ResourceManager.GetString("APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!.
        /// </summary>
        public static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string AUGUST {
            get {
                return ResourceManager.GetString("AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABBRECHEN.
        /// </summary>
        public static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGNORIEREN.
        /// </summary>
        public static string BTN_IGNORE {
            get {
                return ResourceManager.GetString("BTN_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEHR.
        /// </summary>
        public static string BTN_MORE {
            get {
                return ResourceManager.GetString("BTN_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSCHIEBEN.
        /// </summary>
        public static string BTN_MOVE {
            get {
                return ResourceManager.GetString("BTN_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEIN.
        /// </summary>
        public static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIEDERHOLEN.
        /// </summary>
        public static string BTN_RETRY {
            get {
                return ResourceManager.GetString("BTN_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEICHERN.
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JA.
        /// </summary>
        public static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrecheen.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANWENDUNG AUSFÜHREN
        ///Die Anwendung läuft bereits und kann nicht ein zweites Mal gestartet werden..
        /// </summary>
        public static string CANTSTARTUPTWICE {
            get {
                return ResourceManager.GetString("CANTSTARTUPTWICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   x Anwendung schließen.
        /// </summary>
        public static string CONMENU_CLOSEAPP {
            get {
                return ResourceManager.GetString("CONMENU_CLOSEAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;beliebige Taste zur Rückkehr ins Menü&gt;.
        /// </summary>
        public static string CONMENU_RETURNTOMENU {
            get {
                return ResourceManager.GetString("CONMENU_RETURNTOMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   x zurück zum vorherigen Menü.
        /// </summary>
        public static string CONMENU_RETURNTOPREVIOUS {
            get {
                return ResourceManager.GetString("CONMENU_RETURNTOPREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (A)bbrechen, (W)iederholen oder (I)gnorieren.
        /// </summary>
        public static string CONSOLE_ABORT_RETRY_IGNORE {
            get {
                return ResourceManager.GetString("CONSOLE_ABORT_RETRY_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (O)k oder (A)bbrechen.
        /// </summary>
        public static string CONSOLE_OK_CANCEL {
            get {
                return ResourceManager.GetString("CONSOLE_OK_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beliebige Taste zum Fortfahren...
        /// </summary>
        public static string CONSOLE_PRESS_KEY {
            get {
                return ResourceManager.GetString("CONSOLE_PRESS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (W)iederholen oder (A)bbrechen.
        /// </summary>
        public static string CONSOLE_RETRY_CANCEL {
            get {
                return ResourceManager.GetString("CONSOLE_RETRY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (J)a oder (N)ein.
        /// </summary>
        public static string CONSOLE_YES_NO {
            get {
                return ResourceManager.GetString("CONSOLE_YES_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (J)a, (N)ein oder (A)bbrechen.
        /// </summary>
        public static string CONSOLE_YES_NO_CANCEL {
            get {
                return ResourceManager.GetString("CONSOLE_YES_NO_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tage vorher.
        /// </summary>
        public static string DATE_BEFOREDAYS {
            get {
                return ResourceManager.GetString("DATE_BEFOREDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Stunden vorher.
        /// </summary>
        public static string DATE_BEFOREHOURS {
            get {
                return ResourceManager.GetString("DATE_BEFOREHOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minuten vorher.
        /// </summary>
        public static string DATE_BEFOREMINUTES {
            get {
                return ResourceManager.GetString("DATE_BEFOREMINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Monate vorher.
        /// </summary>
        public static string DATE_BEFOREMONTHS {
            get {
                return ResourceManager.GetString("DATE_BEFOREMONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Jahre vorher.
        /// </summary>
        public static string DATE_BEVORYEARS {
            get {
                return ResourceManager.GetString("DATE_BEVORYEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Übersetzer der DB ist keine Befehlszeichenfolge für den Befehl {0} definiert..
        /// </summary>
        public static string DBTRANS_NOCOMMANDDEFINED {
            get {
                return ResourceManager.GetString("DBTRANS_NOCOMMANDDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL Server.
        /// </summary>
        public static string DBTYPE_AZURESQL {
            get {
                return ResourceManager.GetString("DBTYPE_AZURESQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirebirdSQL eingebettet.
        /// </summary>
        public static string DBTYPE_FIREBIRDEMB {
            get {
                return ResourceManager.GetString("DBTYPE_FIREBIRDEMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirebirdSQL Server.
        /// </summary>
        public static string DBTYPE_FIREBIRDSQL {
            get {
                return ResourceManager.GetString("DBTYPE_FIREBIRDSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL-Server.
        /// </summary>
        public static string DBTYPE_MSSQL {
            get {
                return ResourceManager.GetString("DBTYPE_MSSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODBC-Datenbank.
        /// </summary>
        public static string DBTYPE_ODBC {
            get {
                return ResourceManager.GetString("DBTYPE_ODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLE-Datenbank.
        /// </summary>
        public static string DBTYPE_OLEDB {
            get {
                return ResourceManager.GetString("DBTYPE_OLEDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle DB-Server.
        /// </summary>
        public static string DBTYPE_ORACLE {
            get {
                return ResourceManager.GetString("DBTYPE_ORACLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL-Server.
        /// </summary>
        public static string DBTYPE_POSTGRESQL {
            get {
                return ResourceManager.GetString("DBTYPE_POSTGRESQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezember.
        /// </summary>
        public static string DECEMBER {
            get {
                return ResourceManager.GetString("DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Listenvariablen ist nicht erlaubt.
        /// </summary>
        public static string ERR_ADDTOLISTNOTALLOWED {
            get {
                return ResourceManager.GetString("ERR_ADDTOLISTNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthält nicht erlaubte Zeichen. (erlaubt sind: {0}.
        /// </summary>
        public static string ERR_ALLOWEDCHARS {
            get {
                return ResourceManager.GetString("ERR_ALLOWEDCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Anwendungspfad kann nicht aufgelöst werden.
        /// </summary>
        public static string ERR_APPPATHNOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_APPPATHNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zuweisung eines Wertes an ein VariableScript ist nicht möglich.
        /// </summary>
        public static string ERR_ASSIGNVALUETOSAFIPTNOTALLOWED {
            get {
                return ResourceManager.GetString("ERR_ASSIGNVALUETOSAFIPTNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ darf nicht gleichzeit mit den Attributen AFTable und AFSiblingTable versehen werden..
        /// </summary>
        public static string ERR_CANTBETABLEANDSIBLING {
            get {
                return ResourceManager.GetString("ERR_CANTBETABLEANDSIBLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} implementiert die IController-Schnittstelle nicht.
        /// </summary>
        public static string ERR_CONTROLLER_MISSINGINTERFACE {
            get {
                return ResourceManager.GetString("ERR_CONTROLLER_MISSINGINTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} implementiert keine Eigenschaft &apos;Instance&apos; für den Zugriff auf die Controller-Instanz.
        /// </summary>
        public static string ERR_CONTROLLER_NOINSTANCE {
            get {
                return ResourceManager.GetString("ERR_CONTROLLER_NOINSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlende Quelle zum Kopieren von.
        /// </summary>
        public static string ERR_COPY_MISSINGSOURCE {
            get {
                return ResourceManager.GetString("ERR_COPY_MISSINGSOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vor der Verwendung von Encrypt muss CreateKey aufgerufen werden, um den entsprechenden Schlüssel zu erzeugen.
        /// </summary>
        public static string ERR_AFYPT_MISSINGKEY {
            get {
                return ResourceManager.GetString("ERR_AFYPT_MISSINGKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befehl {0} ist nicht verfügbar ({1}).
        /// </summary>
        public static string ERR_CTRL_COMMANDNOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_CTRL_COMMANDNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methode {0} hat mehr als ein AFCommand-Attribut.
        /// </summary>
        public static string ERR_CTRL_TOMANYCOMMANDS {
            get {
                return ResourceManager.GetString("ERR_CTRL_TOMANYCOMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master ist nicht vom Typ {0}.
        /// </summary>
        public static string ERR_CTRL_WRONGMASTERTYPE {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGMASTERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Methode {0} der Klasse {1} muss PUBLIC definiert sein und darf nicht STATIC sein.
        /// </summary>
        public static string ERR_CTRL_WRONGMETHOD {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befehl {0} in Controller {1} kann nicht verwendet werden, da ein Befehl mit demselben Namen bereits existiert.
        /// </summary>
        public static string ERR_CTRL_WRONGNAME {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der erste Parameter der Methode {0} der als Command gekennzeichneten Klasse {1} muss vom Typ AF.CORE.CommandData sein.
        /// </summary>
        public static string ERR_CTRL_WRONGPARAMETER {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rückgabe der Methode {0} der als Command markierten Klasse {1} muss vom Typ AF.CORE.CommandResult sein.
        /// </summary>
        public static string ERR_CTRL_WRONGRETURN {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGRETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicher ist nicht vom Typ {0}.
        /// </summary>
        public static string ERR_CTRL_WRONGSTORAGETYPE {
            get {
                return ResourceManager.GetString("ERR_CTRL_WRONGSTORAGETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank nicht zugewiesen/konfigurier.
        /// </summary>
        public static string ERR_DATABSENOTASSIGNED {
            get {
                return ResourceManager.GetString("ERR_DATABSENOTASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kann nicht größer als {0:d} sein.
        /// </summary>
        public static string ERR_DATECANNOTBEHIGHER {
            get {
                return ResourceManager.GetString("ERR_DATECANNOTBEHIGHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kann nicht kleiner sein als {0:d}.
        /// </summary>
        public static string ERR_DATECANNOTBELOWER {
            get {
                return ResourceManager.GetString("ERR_DATECANNOTBELOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kennwort darf nicht leer sein..
        /// </summary>
        public static string ERR_EMPTYPASSWORDNOTALLOWED {
            get {
                return ResourceManager.GetString("ERR_EMPTYPASSWORDNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei enthält keine Verzeichnisinformationen..
        /// </summary>
        public static string ERR_FILE_NODIRECTORY {
            get {
                return ResourceManager.GetString("ERR_FILE_NODIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei {0} nicht gefunden.
        /// </summary>
        public static string ERR_FILE_NOTFOUND {
            get {
                return ResourceManager.GetString("ERR_FILE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReader ist nicht verfügbar.
        /// </summary>
        public static string ERR_GETREADER_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("ERR_GETREADER_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Band mit dem Namen {0} existiert immer.
        /// </summary>
        public static string ERR_GRID_BANDALLWASEXIST {
            get {
                return ResourceManager.GetString("ERR_GRID_BANDALLWASEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungspfad aus AF.App ist nicht verfügbar. Weisen Sie ein geeignetes Anwendungsobjekt zu.
        /// </summary>
        public static string ERR_MISSINGAPPPATH {
            get {
                return ResourceManager.GetString("ERR_MISSINGAPPPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ, von dem die Tabelle erbt, wurde nicht übergeben (AFSiblingTable.SiblingType)..
        /// </summary>
        public static string ERR_MISSINGSIBLINGTYPE {
            get {
                return ResourceManager.GetString("ERR_MISSINGSIBLINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist eine Tabelle, hat aber keine TableId &gt; 0.
        /// </summary>
        public static string ERR_MISSINGTABLEID {
            get {
                return ResourceManager.GetString("ERR_MISSINGTABLEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist ein View, hat aber keine ViewId &gt; 0.
        /// </summary>
        public static string ERR_MISSINGVIEWID {
            get {
                return ResourceManager.GetString("ERR_MISSINGVIEWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz Typ {0} hat keine Typbeschreibung oder ist keine Tabelle.
        /// </summary>
        public static string ERR_MISSTYPEDESCRIPTION {
            get {
                return ResourceManager.GetString("ERR_MISSTYPEDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge muss ein Vielfaches von 8 sei.
        /// </summary>
        public static string ERR_MUSTMULTIPLEOFEIGHT {
            get {
                return ResourceManager.GetString("ERR_MUSTMULTIPLEOFEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat keine Datenbank zugewiesen. Vielleicht sollten Sie ReadChilds überschreiben.
        /// </summary>
        public static string ERR_NODBCHILDS {
            get {
                return ResourceManager.GetString("ERR_NODBCHILDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat keine Datenbank zugewiesen. Möglicherweise sollten Sie ReadRelated überschreiben.
        /// </summary>
        public static string ERR_NODBRELATED {
            get {
                return ResourceManager.GetString("ERR_NODBRELATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Feld {0} verfügbar.
        /// </summary>
        public static string ERR_NOFIELD {
            get {
                return ResourceManager.GetString("ERR_NOFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein physisches Laufwerk: {0}.
        /// </summary>
        public static string ERR_NOREALDRIVE {
            get {
                return ResourceManager.GetString("ERR_NOREALDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt kein Objekt mit der ID {0} in der Datenbank.
        /// </summary>
        public static string ERR_NORECORDWITHID {
            get {
                return ResourceManager.GetString("ERR_NORECORDWITHID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthält nicht erlaubte Zeichen. (nicht erlaubt sind: {0}.
        /// </summary>
        public static string ERR_NOTALLOWEDCHARS {
            get {
                return ResourceManager.GetString("ERR_NOTALLOWEDCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein Benutzer angemeldet..
        /// </summary>
        public static string ERR_NOUSERLOGGEDIN {
            get {
                return ResourceManager.GetString("ERR_NOUSERLOGGEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL zuweisen ist nicht erlaubt.
        /// </summary>
        public static string ERR_NULLNOTALLOWED {
            get {
                return ResourceManager.GetString("ERR_NULLNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert ohne Namen ({0}).
        /// </summary>
        public static string ERR_PARSER_NONAME {
            get {
                return ResourceManager.GetString("ERR_PARSER_NONAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Name für Parameter ({0}).
        /// </summary>
        public static string ERR_PARSER_WRONGNAME {
            get {
                return ResourceManager.GetString("ERR_PARSER_WRONGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Pfad &apos;{0}&apos; existiert nicht.
        /// </summary>
        public static string ERR_PATHNOTEXIST {
            get {
                return ResourceManager.GetString("ERR_PATHNOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die zu schreibenden Felder müssen beim Einfügen angegeben werden.
        /// </summary>
        public static string ERR_QBUIDLER_INSERTFIELDS {
            get {
                return ResourceManager.GetString("ERR_QBUIDLER_INSERTFIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Alias {0} wird bereits verwendet.
        /// </summary>
        public static string ERR_QBUILDER_ALIASNOTUNIQUE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_ALIASNOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBy kann an dieser Stelle nicht verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_GROUPBYNOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_GROUPBYNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBy kann nur für Select angegeben werden..
        /// </summary>
        public static string ERR_QBUILDER_GROUPBYSELECT {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_GROUPBYSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} kann in der Verknüpfung nicht verwendet werden. Es gibt keine Typbeschreibung.
        /// </summary>
        public static string ERR_QBUILDER_JOINNODESC {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_JOINNODESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} ist weder Tabelle noch View und kann daher nicht im Join verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_JOINNOTTABLEORVIEW {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_JOINNOTTABLEORVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join kann nur für Select angegeben werden.
        /// </summary>
        public static string ERR_QBUILDER_JOINSELECT {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_JOINSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nur nach einem Where verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_NEEDWHERE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_NEEDWHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} ist weder als Tabelle noch als View gekennzeichnet. Der QueryBuilder kann nicht mit dem Typ verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_NOTABLEORVIEW {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_NOTABLEORVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht nach Select, Insert, Update oder Delete verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_NOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_NOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nur nach einem Where verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_ONLYAFTERWHERE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_ONLYAFTERWHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThenBy kann nur nach GroupBy, SortBy, ThenBy oder ThenDescBy verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_THENBYNOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_THENBYNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThenBy kann nur für Select angegeben werden.
        /// </summary>
        public static string ERR_QBUILDER_THENBYSELECT {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_THENBYSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anzahl der Datensätze muss &gt; 0 sein.
        /// </summary>
        public static string ERR_QBUILDER_TOPRECORDS {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_TOPRECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top kann nur mit Select verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_TOPSELECT {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_TOPSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top kann nicht mehr als einmal verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_TOPWRONGUSE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_TOPWRONGUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die zu aktualisierenden Felder müssen für Update angegeben werden.
        /// </summary>
        public static string ERR_QBUILDER_UPDATEFIELDS {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_UPDATEFIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anzahl der Werte stimmt nicht mit der Anzahl der angegebenen Felder überein.
        /// </summary>
        public static string ERR_QBUILDER_VALUESMISMATCH {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_VALUESMISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werte können nur beim Einfügen oder Aktualisieren angegeben werden.
        /// </summary>
        public static string ERR_QBUILDER_VALUESWRONGUSE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_VALUESWRONGUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo kann nur nach Select, Update oder Delete verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_WHERESELECT {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_WHERESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wo kann nicht mehr als einmal in einer Ebene verwendet werden. Verwenden Sie stattdessen And, Or, etc.
        /// </summary>
        public static string ERR_QBUILDER_WHEREWRONGUSE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_WHEREWRONGUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Typ {0} ist keine TypeDescription verfügbar. QueryBuilder kann nicht mit diesem Typ verwendet werden.
        /// </summary>
        public static string ERR_QBUILDER_WRONGTYPE {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_WRONGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update oder Delete sind für den Typ {0} nicht verfügbar, da der Typ eine Ansicht darstellt (nur Select ist verfügbar).
        /// </summary>
        public static string ERR_QBUILDER_WRONGVIEW {
            get {
                return ResourceManager.GetString("ERR_QBUILDER_WRONGVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Datensatz wurde in der Zwischenzeit geändert.
        /// </summary>
        public static string ERR_RECORDCHANGED {
            get {
                return ResourceManager.GetString("ERR_RECORDCHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat die gleiche TableId {1} wie {2}.
        /// </summary>
        public static string ERR_SAMETABLEID {
            get {
                return ResourceManager.GetString("ERR_SAMETABLEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat denselben Tabellennamen {1} wie {2}.
        /// </summary>
        public static string ERR_SAMETABLENAME {
            get {
                return ResourceManager.GetString("ERR_SAMETABLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat die gleiche ViewId {1} wie {2}.
        /// </summary>
        public static string ERR_SAMEVIEWID {
            get {
                return ResourceManager.GetString("ERR_SAMEVIEWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} hat denselben ViewName {1} wie {2}.
        /// </summary>
        public static string ERR_SAMEVIEWNAME {
            get {
                return ResourceManager.GetString("ERR_SAMEVIEWNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitsanbieter nicht zugewiesen/konfigurier.
        /// </summary>
        public static string ERR_SECPROVIDERNOTASSIGNED {
            get {
                return ResourceManager.GetString("ERR_SECPROVIDERNOTASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Tabelle {0}.
        /// </summary>
        public static string ERR_TABLEAFEATING {
            get {
                return ResourceManager.GetString("ERR_TABLEAFEATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist eine Tabelle, hat aber eine TableId &lt; 100. TableIds &lt; 100 sind für interne AF3-Tabellen reserviert.
        /// </summary>
        public static string ERR_TABLEIDRESERVED {
            get {
                return ResourceManager.GetString("ERR_TABLEIDRESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist eine Tabelle, aber Version ist nicht &gt; 0. Die Version muss immer &gt; 0 sein.
        /// </summary>
        public static string ERR_TABLEIDTOSMALL {
            get {
                return ResourceManager.GetString("ERR_TABLEIDTOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestens {0} Zeichen sind erforderlich.
        /// </summary>
        public static string ERR_TOFEWCHARS {
            get {
                return ResourceManager.GetString("ERR_TOFEWCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viele Zeichen. Nur {0} Zeichen erlaubt.
        /// </summary>
        public static string ERR_TOMUCHCHARS {
            get {
                return ResourceManager.GetString("ERR_TOMUCHCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name muss mit dem Zeichen # beginnen und enden.
        /// </summary>
        public static string ERR_TRANS_WRONGNAME {
            get {
                return ResourceManager.GetString("ERR_TRANS_WRONGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} enthält kein Feld für den Primärschlüssel.
        /// </summary>
        public static string ERR_TYPE_DOES_NOT_CONTAIN_KEY {
            get {
                return ResourceManager.GetString("ERR_TYPE_DOES_NOT_CONTAIN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} enthält kein Feld &quot;geändert&quot;.
        /// </summary>
        public static string ERR_TYPE_NOT_CONTAIN_CHANGED {
            get {
                return ResourceManager.GetString("ERR_TYPE_NOT_CONTAIN_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} enthält kein Feld &quot;erstellt&quot;.
        /// </summary>
        public static string ERR_TYPE_NOT_CONTAIN_AFEATED {
            get {
                return ResourceManager.GetString("ERR_TYPE_NOT_CONTAIN_AFEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} kann nicht gleichzeitig Tabelle und Ansicht sein.
        /// </summary>
        public static string ERR_TYPECANNOTBETABLEANDVIEW {
            get {
                return ResourceManager.GetString("ERR_TYPECANNOTBETABLEANDVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Datentyp {0} kann nicht als Feld verwendet werden.
        /// </summary>
        public static string ERR_TYPECANNOTBEUSEDASFIELD {
            get {
                return ResourceManager.GetString("ERR_TYPECANNOTBEUSEDASFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} implementiert nicht AF.CORE.IBindable.
        /// </summary>
        public static string ERR_TYPEISNOTBINDABLE {
            get {
                return ResourceManager.GetString("ERR_TYPEISNOTBINDABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist keine Tabelle.
        /// </summary>
        public static string ERR_TYPEISNOTTABLE {
            get {
                return ResourceManager.GetString("ERR_TYPEISNOTTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist keine Tabelle oder View. Diese Methode ist nur für Tabellen oder Views geeignet.
        /// </summary>
        public static string ERR_TYPEISNOTTABLEORVIEW {
            get {
                return ResourceManager.GetString("ERR_TYPEISNOTTABLEORVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist kein View.
        /// </summary>
        public static string ERR_TYPEISNOTVIEW {
            get {
                return ResourceManager.GetString("ERR_TYPEISNOTVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es kann keine Datenbank für {0} gefunden werden.
        /// </summary>
        public static string ERR_TYPEMISSINGDB {
            get {
                return ResourceManager.GetString("ERR_TYPEMISSINGDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ der Quelle ist nicht gleich diesem Typ.
        /// </summary>
        public static string ERR_TYPESNOTEQUAL {
            get {
                return ResourceManager.GetString("ERR_TYPESNOTEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unbekannter Controller.
        /// </summary>
        public static string ERR_UNKNOWNCONTROLLER {
            get {
                return ResourceManager.GetString("ERR_UNKNOWNCONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ, von dem die Tabelle erbt, ist unbekannt(AFSiblingTable.SiblingType)..
        /// </summary>
        public static string ERR_UNKNOWNSIBLINGTYPE {
            get {
                return ResourceManager.GetString("ERR_UNKNOWNSIBLINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login als Benutzer SYSTEM ist nicht erlaubt..
        /// </summary>
        public static string ERR_USERSYSTEMNOTALLOWED {
            get {
                return ResourceManager.GetString("ERR_USERSYSTEMNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert muss zwischen {0} und {1} liegen.
        /// </summary>
        public static string ERR_VALUEMUSTBETWEEN {
            get {
                return ResourceManager.GetString("ERR_VALUEMUSTBETWEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der aktuelle Wert ist kein Element der Liste.
        /// </summary>
        public static string ERR_VALUENOTINLIST {
            get {
                return ResourceManager.GetString("ERR_VALUENOTINLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wird bereits verwendet, muss aber eindeutig sein..
        /// </summary>
        public static string ERR_VALUENOTUNIQUE {
            get {
                return ResourceManager.GetString("ERR_VALUENOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert kann nicht größer/höher als {0} sein.
        /// </summary>
        public static string ERR_VALUETOBIG {
            get {
                return ResourceManager.GetString("ERR_VALUETOBIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert kann nicht kleiner als {0} sein.
        /// </summary>
        public static string ERR_VALUETOSMALL {
            get {
                return ResourceManager.GetString("ERR_VALUETOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist eine Ansicht, hat aber eine ViewId &lt; 100. ViewIds &lt; 100 sind für AF3-interne Ansichten reserviert.
        /// </summary>
        public static string ERR_VIEWIDRESERVRED {
            get {
                return ResourceManager.GetString("ERR_VIEWIDRESERVRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ {0} ist ein View, aber Version ist nicht &gt; 0. Die Version muss immer &gt; 0 sein.
        /// </summary>
        public static string ERR_VIEWIDTOSMALL {
            get {
                return ResourceManager.GetString("ERR_VIEWIDTOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays müssen die gleiche Länge habe.
        /// </summary>
        public static string ERR_WRONGARRAYLENGTH {
            get {
                return ResourceManager.GetString("ERR_WRONGARRAYLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Array-Typ. Array muss vom Typ {0} sein..
        /// </summary>
        public static string ERR_WRONGARRAYTYPE {
            get {
                return ResourceManager.GetString("ERR_WRONGARRAYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Skript-ID {0}.
        /// </summary>
        public static string ERR_WRONGSAFIPTID {
            get {
                return ResourceManager.GetString("ERR_WRONGSAFIPTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ von der die Tabelle erbt, ist beschreibt keine Tabelle (AFSiblingTable.SiblingType)..
        /// </summary>
        public static string ERR_WRONGSIBLINGTYPE {
            get {
                return ResourceManager.GetString("ERR_WRONGSIBLINGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Länge des Wertes muss zwischen {0} und {1} Zeichen liegen.
        /// </summary>
        public static string ERR_WRONGSTRINGLENGTH {
            get {
                return ResourceManager.GetString("ERR_WRONGSTRINGLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion kann nicht abgeschlossen werden. Es ist keine Transaktion aktiv.
        /// </summary>
        public static string ERROR_CANTCOMMITNOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_CANTCOMMITNOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion kann nicht rückgängig gemacht werden. Es ist keine Transaktion aktiv.
        /// </summary>
        public static string ERROR_CANTROLLBACKNOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_CANTROLLBACKNOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ransaktion kann nicht gestartet werden. Es ist bereits eine Transaktion aktiv.
        /// </summary>
        public static string ERROR_CANTSTARTTRANSACTIONWHILETRANSACTIONEXIST {
            get {
                return ResourceManager.GetString("ERROR_CANTSTARTTRANSACTIONWHILETRANSACTIONEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Methode {0} muss als public static definiert sein, um als COMMAND verwendet werden zu können.
        /// </summary>
        public static string ERROR_COMMANDMETHODMUSTBESTATIC {
            get {
                return ResourceManager.GetString("ERROR_COMMANDMETHODMUSTBESTATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Festschreiben einer Transaktion ist ein Fehler aufgetreten.
        /// </summary>
        public static string ERROR_COMMITTRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_COMMITTRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Festschreiben der Transaktion. Siehe Innerexception für weitere Informationen.
        /// </summary>
        public static string ERROR_COMMITTRANSACTION1 {
            get {
                return ResourceManager.GetString("ERROR_COMMITTRANSACTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Konstruktor kann nicht ohne Angabe der Datenbank verwendet werden.
        /// </summary>
        public static string ERROR_DBCONSTRUCTORCANTUSEDWITHOUTPARAMETER {
            get {
                return ResourceManager.GetString("ERROR_DBCONSTRUCTORCANTUSEDWITHOUTPARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion existiert bereits.
        /// </summary>
        public static string ERROR_DBTRANSACTIONEXISTS {
            get {
                return ResourceManager.GetString("ERROR_DBTRANSACTIONEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt bereits eine offene Transaktion. Eine neue Transaktion kann nicht erstellt werden.
        /// </summary>
        public static string ERROR_DBTRANSACTIONEXISTS1 {
            get {
                return ResourceManager.GetString("ERROR_DBTRANSACTIONEXISTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Löschung wurde abgebrochen.
        /// </summary>
        public static string ERROR_DELETECANCELED {
            get {
                return ResourceManager.GetString("ERROR_DELETECANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Verzeichnis &apos;{0}&apos; befindet sich nicht auf einem physischen Laufwerk, sondern stellt ein UNC-Verzeichnis dar, für das keine Seriennummer verfügbar ist.
        /// </summary>
        public static string ERROR_DIRECTORYINFO_NOPHYSICALDRIVE {
            get {
                return ResourceManager.GetString("ERROR_DIRECTORYINFO_NOPHYSICALDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Methode muss in der konkreten Steuerung des Modells implementiert werden.
        /// </summary>
        public static string ERROR_IMPELEMENTINCHILDCONTROLLER {
            get {
                return ResourceManager.GetString("ERROR_IMPELEMENTINCHILDCONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} enthält kein Systemfeld für PrimaryKey. IsUnique wird daher nicht unterstützt.
        /// </summary>
        public static string ERROR_ISUNIQUENOTAVAILABLE {
            get {
                return ResourceManager.GetString("ERROR_ISUNIQUENOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} hat keine Eigenschaft mit dem Namen {1}, an die er gebunden werden kann. (GET fehlt.
        /// </summary>
        public static string ERROR_MISSINGBINDINGGETTER {
            get {
                return ResourceManager.GetString("ERROR_MISSINGBINDINGGETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} hat keine Eigenschaft mit dem Namen {1}, an die er gebunden werden kann. (SET fehlt.
        /// </summary>
        public static string ERROR_MISSINGBINDINGSETTER {
            get {
                return ResourceManager.GetString("ERROR_MISSINGBINDINGSETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Datenbank gefunden. Weisen Sie eine Datenbank zu, bevor Sie diese Methode verwenden.
        /// </summary>
        public static string ERROR_MISSINGDATABASE {
            get {
                return ResourceManager.GetString("ERROR_MISSINGDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feldname für Zusammenfassung nicht angegeben..
        /// </summary>
        public static string ERROR_MISSINGFIELDNAME {
            get {
                return ResourceManager.GetString("ERROR_MISSINGFIELDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} hat kein Feld, das die Eigenschaft eSystemFieldFlag.Key besitzt.
        /// </summary>
        public static string ERROR_MISSINGKEYFIELD {
            get {
                return ResourceManager.GetString("ERROR_MISSINGKEYFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ/Klasse {0} enthält kein Feld, das als PrimaryKey (Feldattribut) gekennzeichnet ist.
        /// </summary>
        public static string ERROR_MISSINGPRIMARYKEY {
            get {
                return ResourceManager.GetString("ERROR_MISSINGPRIMARYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} ist weder mit dem Attribut TABLE noch mit dem Attribut VIEW versehen.
        /// </summary>
        public static string ERROR_MISSINGTABLEATTRIBUTE {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTABLEATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ/die Klasse {0} enthält kein als TimestampChanged (Feldattribut) gekennzeichnetes Feld.
        /// </summary>
        public static string ERROR_MISSINGTIMESTAMPCHANGED {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTIMESTAMPCHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ/die Klasse {0} enthält kein als TimestampCreated (Attribut Field) gekennzeichnetes Feld.
        /// </summary>
        public static string ERROR_MISSINGTIMESTAMPAFEATED {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTIMESTAMPAFEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Typbeschreibung (TypeDescription) übergeben.
        /// </summary>
        public static string ERROR_MISSINGTYPEDESCRIPTION {
            get {
                return ResourceManager.GetString("ERROR_MISSINGTYPEDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration muss vom Typ FirebirdConfiguration sein.
        /// </summary>
        public static string ERROR_MUSTBEFIREBIRDCONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEFIREBIRDCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Übersetzer muss vom Typ FirebirdTranslator sein.
        /// </summary>
        public static string ERROR_MUSTBEFIREBIRDTRANSLATOR {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEFIREBIRDTRANSLATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muss in konkreten, nicht abstrakten Klassen überschrieben werden.
        /// </summary>
        public static string ERROR_MUSTBEOVERWRITEN {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEOVERWRITEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration muss vom Typ PostgreConfiguration sein.
        /// </summary>
        public static string ERROR_MUSTBEPOSTGRECONFIGURATION {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEPOSTGRECONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Übersetzer muss vom Typ PostgreTranslator sein.
        /// </summary>
        public static string ERROR_MUSTBEPOSTGRETRANSLATOR {
            get {
                return ResourceManager.GetString("ERROR_MUSTBEPOSTGRETRANSLATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keine aktive Verbindung.
        /// </summary>
        public static string ERROR_NOACTIVECONNECTION {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVECONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keine offene Verbindung, zu der eine Transaktion erstellt werden kann.
        /// </summary>
        public static string ERROR_NOACTIVECONNECTION1 {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVECONNECTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keine offene Transaktion.
        /// </summary>
        public static string ERROR_NOACTIVETRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVETRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt keine offene Transaktion.
        /// </summary>
        public static string ERROR_NOACTIVETRANSACTION1 {
            get {
                return ResourceManager.GetString("ERROR_NOACTIVETRANSACTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Anwendungsobjekt zugewiesen.
        /// </summary>
        public static string ERROR_NOAPPASSIGNED {
            get {
                return ResourceManager.GetString("ERROR_NOAPPASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} verfügt nicht über ein Feld mit dem Namen {1}.
        /// </summary>
        public static string ERROR_NOFIELDINTYPE {
            get {
                return ResourceManager.GetString("ERROR_NOFIELDINTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemfelder sind nur erlaubt, wenn der Typ mit dem TABLE-Attribut oder dem VIEW-Attribut versehen wurde.
        /// </summary>
        public static string ERROR_NOSYSTEMFIELDSALLOWED {
            get {
                return ResourceManager.GetString("ERROR_NOSYSTEMFIELDSALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Methode muss in der konkreten Datenbankverbindungsklasse implementiert werden..
        /// </summary>
        public static string ERROR_NOTIMPLEMENTEDINBASE {
            get {
                return ResourceManager.GetString("ERROR_NOTIMPLEMENTEDINBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} ist nicht serialisierbar. Das Objekt kann nicht serialisiert werden.
        /// </summary>
        public static string ERROR_OBJECTNOTSERIALIZABLE {
            get {
                return ResourceManager.GetString("ERROR_OBJECTNOTSERIALIZABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Rollback der Transaktion. Siehe Innerexception für weitere Informationen.
        /// </summary>
        public static string ERROR_ROLLBACKTRANSACTION {
            get {
                return ResourceManager.GetString("ERROR_ROLLBACKTRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Speichervorgang wurde abgebrochen.
        /// </summary>
        public static string ERROR_SAVECANCELED {
            get {
                return ResourceManager.GetString("ERROR_SAVECANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Assembly konnte nicht erstellt werden.
        /// </summary>
        public static string ERROR_SAFIPTINGCANTAFEATEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SAFIPTINGCANTAFEATEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt der Klasse {0} konnte nicht erstellt werden.
        /// </summary>
        public static string ERROR_SAFIPTINGCANTAFEATEOBJECT {
            get {
                return ResourceManager.GetString("ERROR_SAFIPTINGCANTAFEATEOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Fehler beim Kompilieren der Assembly.
        /// </summary>
        public static string ERROR_SAFIPTINGERRORWHILECOMPILEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SAFIPTINGERRORWHILECOMPILEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Assembly.
        ///{0}&quot;
        ///&quot;Fehler beim Erstellen des Objekt.
        /// </summary>
        public static string ERROR_SAFIPTINGERRORWHILEAFEATEASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_SAFIPTINGERRORWHILEAFEATEASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ERROR_SAFIPTINGERRORWHILEAFEATEOBJECT {
            get {
                return ResourceManager.GetString("ERROR_SAFIPTINGERRORWHILEAFEATEOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Maske: {0}.
        /// </summary>
        public static string ERROR_STRINGMASKERROR {
            get {
                return ResourceManager.GetString("ERROR_STRINGMASKERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Systemfeld {0} kann zweimal in der Klasse {1} definiert werden.
        /// </summary>
        public static string ERROR_SYSTEMFIELDDUPLICATE {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDDUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Systemfeld {0} kann nur von einer Entität vom Typ TABLE oder VIEW verwendet werden. (die Klasse {1} muss mit dem Attribut TABLE oder VIEW versehen sein).
        /// </summary>
        public static string ERROR_SYSTEMFIELDNOTALLOWED {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Systemfeld {0} muss als persistent gekennzeichnet sein.
        /// </summary>
        public static string ERROR_SYSTEMFIELDNOTMARKEDASPERSISTANT {
            get {
                return ResourceManager.GetString("ERROR_SYSTEMFIELDNOTMARKEDASPERSISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die TableID der Tabelle {0} muss größer als 0 sein.
        /// </summary>
        public static string ERROR_TABLEIDTOSMALL {
            get {
                return ResourceManager.GetString("ERROR_TABLEIDTOSMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} enthält kein Feld mit dem Namen {1}. Regel kann nicht hinzugefügt werden.
        /// </summary>
        public static string ERROR_TYPEDOESNTCONTAINFIELD {
            get {
                return ResourceManager.GetString("ERROR_TYPEDOESNTCONTAINFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Schaltflächenkonfiguration/-kombination.
        /// </summary>
        public static string ERROR_UNKNOWNBUTTONS {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWNBUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert darf nicht NULL sein.
        /// </summary>
        public static string ERROR_VALUECANTBENULL {
            get {
                return ResourceManager.GetString("ERROR_VALUECANTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss &gt;= 0 sein.
        /// </summary>
        public static string ERROR_VALUEMUSTBEBIGGERTHENZERO {
            get {
                return ResourceManager.GetString("ERROR_VALUEMUSTBEBIGGERTHENZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} kann nicht gleichzeitig als VIEW und als TABLE markiert sein.
        /// </summary>
        public static string ERROR_VIEWCANTBETABLE {
            get {
                return ResourceManager.GetString("ERROR_VIEWCANTBETABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Typ {0}, der mit dem Attribut VIEW versehen wurde, fehlt die Definition der Abfrage. Die Abfrage des Views muss angegeben werden (entweder über &apos;Query&apos; im View-Attribut oder eine statische Methode &apos;RequestViewQuery&apos; in der Klasse des Typs.
        /// </summary>
        public static string ERROR_VIEWDOENSTCONTAINQUERY {
            get {
                return ResourceManager.GetString("ERROR_VIEWDOENSTCONTAINQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Abfrage vom Typ {0}, die mit dem VIEW-Attribut bereitgestellt wird, fehlt der Platzhalter #FIELDS#, der die abzufragenden Felder darstellt.
        /// </summary>
        public static string ERROR_VIEWDOESNTCONTAINFIELDS {
            get {
                return ResourceManager.GetString("ERROR_VIEWDOESNTCONTAINFIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Konvertieren des Bildes aus dem Datenbankdatenstrom.
        /// </summary>
        public static string ERROR_WHILECONVERTIMAGEFROMBYTEARRAY {
            get {
                return ResourceManager.GetString("ERROR_WHILECONVERTIMAGEFROMBYTEARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Konvertieren des Bildes in einen Datenstrom..
        /// </summary>
        public static string ERROR_WHILECONVERTIMAGETOBYTEARRAY {
            get {
                return ResourceManager.GetString("ERROR_WHILECONVERTIMAGETOBYTEARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Konvertierung eines Wertes in das Datenbankformat. (Quelltyp: {0}, Zieltyp: {1}.
        /// </summary>
        public static string ERROR_WHILETRANSLATINGTODB {
            get {
                return ResourceManager.GetString("ERROR_WHILETRANSLATINGTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Konvertierung eines Wertes aus dem Datenbankformat. (Quelltyp: {0}, Zieltyp: {1}.
        /// </summary>
        public static string ERROR_WHILETRANSLATIONFROMDB {
            get {
                return ResourceManager.GetString("ERROR_WHILETRANSLATIONFROMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen des Verzeichnisses für die Client-Konfiguration ({0}). {1}.
        /// </summary>
        public static string ERRORAFEATINGMANDANTDIRECTORY {
            get {
                return ResourceManager.GetString("ERRORAFEATINGMANDANTDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER BEIM STARTEN
        ///Beim Starten der Anwendung ist ein Fehler aufgetreten.
        ///{0}&quot;
        ///Fehler beim Erstellen der Datenbank {0.
        /// </summary>
        public static string ERRORONSTARTUP {
            get {
                return ResourceManager.GetString("ERRORONSTARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Datenbank {0}.
        /// </summary>
        public static string ERRORWHILEAFEATINGDATABASE {
            get {
                return ResourceManager.GetString("ERRORWHILEAFEATINGDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Konfiguration des Clients aus der Datei {0} ist ein Fehler aufgetreten. {1}.
        /// </summary>
        public static string ERRORWHILELOADINGMANDATNTCONFIG {
            get {
                return ResourceManager.GetString("ERRORWHILELOADINGMANDATNTCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falscher Benutzername und/oder falsches Passwort.
        /// </summary>
        public static string ERRORWRONGUSERORPASSWORD {
            get {
                return ResourceManager.GetString("ERRORWRONGUSERORPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februar.
        /// </summary>
        public static string FEBRUARY {
            get {
                return ResourceManager.GetString("FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorieren.
        /// </summary>
        public static string IGNORE {
            get {
                return ResourceManager.GetString("IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januar.
        /// </summary>
        public static string JANUARY {
            get {
                return ResourceManager.GetString("JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juli.
        /// </summary>
        public static string JULI {
            get {
                return ResourceManager.GetString("JULI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juni.
        /// </summary>
        public static string JUNE {
            get {
                return ResourceManager.GetString("JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Feld.
        /// </summary>
        public static string LBL_ADDFIELD {
            get {
                return ResourceManager.GetString("LBL_ADDFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string LBL_EDIT {
            get {
                return ResourceManager.GetString("LBL_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; von &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        public static string LBL_PROGRESS {
            get {
                return ResourceManager.GetString("LBL_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle.
        /// </summary>
        public static string LBL_TABLE {
            get {
                return ResourceManager.GetString("LBL_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string LBL_VIEW {
            get {
                return ResourceManager.GetString("LBL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Anmeldename muss mindestens 5 Zeichen lang sein.
        /// </summary>
        public static string LOGINNAMETOSHORT {
            get {
                return ResourceManager.GetString("LOGINNAMETOSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN
        ///Die Anmeldung war nicht erfolgreich. Die Anmeldung wird abgebrochen..
        /// </summary>
        public static string LOGINNOTSUCCESSFULL {
            get {
                return ResourceManager.GetString("LOGINNOTSUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to März.
        /// </summary>
        public static string MARCH {
            get {
                return ResourceManager.GetString("MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string MAY {
            get {
                return ResourceManager.GetString("MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr Informationen.
        /// </summary>
        public static string MOREINFORMATIONS {
            get {
                return ResourceManager.GetString("MOREINFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Tabelle {0}....
        /// </summary>
        public static string MSG_CHECKTABLE {
            get {
                return ResourceManager.GetString("MSG_CHECKTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe View {0}....
        /// </summary>
        public static string MSG_CHECKVIEW {
            get {
                return ResourceManager.GetString("MSG_CHECKVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche View {0}....
        /// </summary>
        public static string MSG_DELETEVIEW {
            get {
                return ResourceManager.GetString("MSG_DELETEVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht erlaubt. Sie haben nicht die erforderliche Berechtigung..
        /// </summary>
        public static string NOTALLOWED {
            get {
                return ResourceManager.GetString("NOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string NOVEMBER {
            get {
                return ResourceManager.GetString("NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktober.
        /// </summary>
        public static string OCTOBER {
            get {
                return ResourceManager.GetString("OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wiederholung stimmt nicht mit dem Passwort überein..
        /// </summary>
        public static string PASSWORDNOTMATCH {
            get {
                return ResourceManager.GetString("PASSWORDNOTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens 8 Zeichen lang sein..
        /// </summary>
        public static string PASSWORDTOSHORT {
            get {
                return ResourceManager.GetString("PASSWORDTOSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frage.
        /// </summary>
        public static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholung.
        /// </summary>
        public static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string SEPTEMBER {
            get {
                return ResourceManager.GetString("SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist archiviert.
        /// </summary>
        public static string SYS_ARCHIVED {
            get {
                return ResourceManager.GetString("SYS_ARCHIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Eigenschaft kennzeichnet einen Datensatz als archiviert..
        /// </summary>
        public static string SYS_ARCHIVED_DESC {
            get {
                return ResourceManager.GetString("SYS_ARCHIVED_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivierte Datensätze/Objekte werden bei Standardoperationen nicht verarbeitet/verwendet (z. B. nicht angezeigt)..
        /// </summary>
        public static string SYS_ARCHIVED_HINT {
            get {
                return ResourceManager.GetString("SYS_ARCHIVED_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sind archiviert.
        /// </summary>
        public static string SYS_ARCHIVED_PLURAL {
            get {
                return ResourceManager.GetString("SYS_ARCHIVED_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archiviert.
        /// </summary>
        public static string SYS_ARCHIVED_SINGULAR {
            get {
                return ResourceManager.GetString("SYS_ARCHIVED_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zeitpunkt der letzten Änderung des Datensatzes/Objekts in der Datenbank.
        /// </summary>
        public static string SYS_CHANGED_DESC {
            get {
                return ResourceManager.GetString("SYS_CHANGED_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Zeitstempel wird automatisch aktualisiert, wenn der Datensatz/das Objekt in der Datenbank gespeichert wird. Bis zur ersten Speicherung lautet der Zeitstempel 01.01.0001..
        /// </summary>
        public static string SYS_CHANGED_HINT {
            get {
                return ResourceManager.GetString("SYS_CHANGED_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geändert am.
        /// </summary>
        public static string SYS_CHANGED_PLURAL {
            get {
                return ResourceManager.GetString("SYS_CHANGED_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geändert am.
        /// </summary>
        public static string SYS_CHANGED_SINGULAR {
            get {
                return ResourceManager.GetString("SYS_CHANGED_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zeitpunkt, zu dem der Datensatz/das Objekt erstmals in der Datenbank gespeichert wurde..
        /// </summary>
        public static string SYS_CREATED_DESC {
            get {
                return ResourceManager.GetString("SYS_CREATED_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Zeitstempel wird automatisch erstellt, wenn die Daten erstmals in der Datenbank gespeichert werden. Bis zu diesem Zeitpunkt ist der Zeitstempel 01.01.0001..
        /// </summary>
        public static string SYS_CREATED_HINT {
            get {
                return ResourceManager.GetString("SYS_CREATED_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erstellt am.
        /// </summary>
        public static string SYS_CREATED_PLURAL {
            get {
                return ResourceManager.GetString("SYS_CREATED_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erstellt am.
        /// </summary>
        public static string SYS_CREATED_SINGULAR {
            get {
                return ResourceManager.GetString("SYS_CREATED_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner, in dem das Element abgelegt werden soll..
        /// </summary>
        public static string SYS_FOLDER_DESC {
            get {
                return ResourceManager.GetString("SYS_FOLDER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string SYS_FOLDER_PLURAL {
            get {
                return ResourceManager.GetString("SYS_FOLDER_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string SYS_FOLDER_SINGULAR {
            get {
                return ResourceManager.GetString("SYS_FOLDER_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die interne ID (Primärschlüssel) des Datensatzes/Objekts in der Datenbankm.
        /// </summary>
        public static string SYS_ID_DESC {
            get {
                return ResourceManager.GetString("SYS_ID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese ID wird automatisch erstellt, wenn er zum ersten Mal in der Datenbank gespeichert wird. Bis zu diesem Zeitpunkt ist die ID leer..
        /// </summary>
        public static string SYS_ID_HINT {
            get {
                return ResourceManager.GetString("SYS_ID_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interne IDs.
        /// </summary>
        public static string SYS_ID_PLURAL {
            get {
                return ResourceManager.GetString("SYS_ID_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interne ID.
        /// </summary>
        public static string SYS_ID_SINGULAR {
            get {
                return ResourceManager.GetString("SYS_ID_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nicht gewählt&gt;.
        /// </summary>
        public static string TXT_NOTSELECTED {
            get {
                return ResourceManager.GetString("TXT_NOTSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unbekannt&gt;.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthält nicht erlaubte Zeichen. (nicht erlaubt sind: {0}).
        /// </summary>
        public static string VALIDATE_NOTALLOWEDCHARS {
            get {
                return ResourceManager.GetString("VALIDATE_NOTALLOWEDCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert darf nicht null sein..
        /// </summary>
        public static string VALUECANNOTBENULL {
            get {
                return ResourceManager.GetString("VALUECANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
