//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AF.WINFORMS.DX.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AF.WINFORMS.DX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Copyright&gt;Copyright (c) 2016-2023 Alternet Software&lt;/Copyright&gt;
        ///  &lt;FileType&gt;c#&lt;/FileType&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;Desc&gt;Identifiers&lt;/Desc&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;numbers&lt;/Name&gt;
        ///      &lt;Desc&gt;Numbers [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string csParser1_XmlScheme {
            get {
                return ResourceManager.GetString("csParser1.XmlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .root {
        ///        background-color:@Window;
        ///        color:@WindowText;        
        ///}        
        ///        
        ///.container {        
        ///        padding:6px;        
        ///}        
        ///        
        ///.card {        
        ///        font: 13px &apos;Segoe UI&apos;;        
        ///        border-radius:3px;        
        ///        background-color:@Window;        
        ///        box-shadow:0px 1px 2px 0px #20000000;        
        ///        color:@WindowText;        
        ///        display:flex;        
        ///}        
        ///        
        ///:root:select .card {        
        ///        background-color:@Hig [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DEFAULT_CSS_TEMPLATE {
            get {
                return ResourceManager.GetString("DEFAULT_CSS_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;div class=&quot;container&quot;&gt;
        ///	&lt;div class=&quot;card&quot;&gt;
        ///		&lt;div class=&quot;stripe&quot; id=&quot;stripe&quot;&gt;&lt;/div&gt;
        ///		&lt;div class=&quot;content&quot;&gt;
        ///			&lt;div class=&quot;top-block&quot;&gt;
        ///				&lt;div class=&quot;caption&quot; id=&quot;caption&quot;&gt;&lt;b&gt;${FIR_NAMEEINZEILIG}&lt;/b&gt;&lt;/div&gt;
        ///				&lt;div class=&quot;statuslink&quot; id=&quot;link&quot;&gt;LINK&lt;/div&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;status&quot; id=&quot;important&quot;&gt;WICHTIG&lt;/div&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;div class=&quot;status&quot; id=&quot;status&quot;&gt;${AUF_STATUS_TEXT}&lt;/div&gt; 
        ///			&lt;/div&gt;
        ///			&lt;div class=&quot;description&quot;&gt;${AUF_AUFGABE}&lt;/div&gt;
        ///			&lt;div class=&quot;bottom-block&quot;&gt;
        ///				&lt;div class=&quot;b [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DEFAULT_HTML_TEMPLATE {
            get {
                return ResourceManager.GetString("DEFAULT_HTML_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Copyright&gt;Copyright (c) 2016-2023 Alternet Software&lt;/Copyright&gt;
        ///  &lt;FileType&gt;html&lt;/FileType&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;numbers&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/S [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string htmlParser1_XmlScheme {
            get {
                return ResourceManager.GetString("htmlParser1.XmlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string LBL_DATABASE {
            get {
                return ResourceManager.GetString("LBL_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout geladen... ähnelt.
        /// </summary>
        internal static string LBL_LAYOUTLOADED {
            get {
                return ResourceManager.GetString("LBL_LAYOUTLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout zurückgesetzt... ähnelt.
        /// </summary>
        internal static string LBL_LAYOUTRESETED {
            get {
                return ResourceManager.GetString("LBL_LAYOUTRESETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout gespeichert... ähnelt.
        /// </summary>
        internal static string LBL_LAYOUTSAVED {
            get {
                return ResourceManager.GetString("LBL_LAYOUTSAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankschema wird geladen... ähnelt.
        /// </summary>
        internal static string LBL_LOADDBSCHEME {
            get {
                return ResourceManager.GetString("LBL_LOADDBSCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lädt... ähnelt.
        /// </summary>
        internal static string LBL_LOADING {
            get {
                return ResourceManager.GetString("LBL_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die max. Länge ähnelt.
        /// </summary>
        internal static string LBL_MAXLENGTH {
            get {
                return ResourceManager.GetString("LBL_MAXLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Methoden ähnelt.
        /// </summary>
        internal static string LBL_METHODS {
            get {
                return ResourceManager.GetString("LBL_METHODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften ähnelt.
        /// </summary>
        internal static string LBL_PROPERTIES {
            get {
                return ResourceManager.GetString("LBL_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Datenquelle auswählen&gt; ähnelt.
        /// </summary>
        internal static string LBL_SELECTDATASOURCE {
            get {
                return ResourceManager.GetString("LBL_SELECTDATASOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle ähnelt.
        /// </summary>
        internal static string LBL_TABLE {
            get {
                return ResourceManager.GetString("LBL_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle/Ansicht ähnelt.
        /// </summary>
        internal static string LBL_TABLEVIEW {
            get {
                return ResourceManager.GetString("LBL_TABLEVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        /// </summary>
        internal static string LBL_TYPE {
            get {
                return ResourceManager.GetString("LBL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        internal static string LBL_VIEW {
            get {
                return ResourceManager.GetString("LBL_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BITTE WARTEN ähnelt.
        /// </summary>
        internal static string LBL_WAIT {
            get {
                return ResourceManager.GetString("LBL_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Spalten verwalten... ähnelt.
        /// </summary>
        internal static string MEN_GRIDCALCEDCOLUMNS {
            get {
                return ResourceManager.GetString("MEN_GRIDCALCEDCOLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Datei exportieren... ähnelt.
        /// </summary>
        internal static string MEN_GRIDEXPORT {
            get {
                return ResourceManager.GetString("MEN_GRIDEXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout\Layout laden... ähnelt.
        /// </summary>
        internal static string MEN_LAYOUTLOAD {
            get {
                return ResourceManager.GetString("MEN_LAYOUTLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout\Layout verwalten... ähnelt.
        /// </summary>
        internal static string MEN_LAYOUTMANAGE {
            get {
                return ResourceManager.GetString("MEN_LAYOUTMANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout\Layout zurücksetzen... ähnelt.
        /// </summary>
        internal static string MEN_LAYOUTRESET {
            get {
                return ResourceManager.GetString("MEN_LAYOUTRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout\Layout speichern... ähnelt.
        /// </summary>
        internal static string MEN_LAYOUTSAVE {
            get {
                return ResourceManager.GetString("MEN_LAYOUTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autom. Spaltenbreite ein/aus ähnelt.
        /// </summary>
        internal static string MEN_TOGGLEAUTOWITH {
            get {
                return ResourceManager.GetString("MEN_TOGGLEAUTOWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fusszeile ein/aus ähnelt.
        /// </summary>
        internal static string MEN_TOGGLEFOOTER {
            get {
                return ResourceManager.GetString("MEN_TOGGLEFOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Copyright&gt;Copyright (c) 2016-2023 Alternet Software&lt;/Copyright&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;numbers&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Na [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string mssqlParser1_XmlScheme {
            get {
                return ResourceManager.GetString("mssqlParser1.XmlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage newtabheader {
            get {
                object obj = ResourceManager.GetObject("newtabheader", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Copyright&gt;Copyright (c) 2016-2023 Alternet Software&lt;/Copyright&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;numbers&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Na [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string sqlParser2_XmlScheme {
            get {
                return ResourceManager.GetString("sqlParser2.XmlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] standardformat {
            get {
                object obj = ResourceManager.GetObject("standardformat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;AlterNET Software&lt;/Author&gt;
        ///  &lt;Copyright&gt;Copyright (c) 2016-2023 Alternet Software&lt;/Copyright&gt;
        ///  &lt;FileType&gt;xml&lt;/FileType&gt;
        ///  &lt;Version&gt;1.5&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/Style&gt;
        ///    &lt;Style&gt;
        ///      &lt;Name&gt;numbers&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///    &lt;/St [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string xmlParser1_XmlScheme {
            get {
                return ResourceManager.GetString("xmlParser1.XmlScheme", resourceCulture);
            }
        }
    }
}
